spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AAS
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8080


